[project]
name = "game"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ortools>=9.14.6206",
    "pandas>=2.3.3",
    "matplotlib>=3.7.0",
    "streamlit>=1.28.0",
]
